version: '3.8'
services:
  fuse-agent:
    container_name: fuse-agent
    build: .
    #restart: always
    env_file: .env
    ports:
        - ${API_PORT}:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./config/config.json:/app/config.json
    expose:
      - ${API_PORT}

