version: '3.8'
services:
  fuse-agent:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
    #restart: always
    env_file: .env
    ports:
        - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${CONFIG_PATH}:/app/config.json
        - ./data:/app/data
    networks:
      - agent_network
    depends_on:
      - agent-redis
      - agent-tx-persistence

  agent-tx-persistence:
    container_name: agent-tx-persistence
    image: txscience/tx-persistence
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    expose:
      - ${MONGO_PORT}
    networks:
      - agent_network

  agent-redis:
    container_name: agent-redis
    image: redis:alpine
    restart: always
    environment: {}
    volumes:
      - /data
    expose:
      - 6379
    command: ["--appendonly", "yes"]
    networks:
      - agent_network

networks:
  agent_network:
    name: ${CONTAINER_NETWORK}
    external: true

