version: '3.8'
services:
  fuse-agent:
    container_name: ${CONTAINER_NAME}
    build: .
    #restart: always
    env_file: .env
    ports:
        - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${CONFIG_PATH}:/app/config.json
    networks:
      - agent_network

  agent-tx-persistence:
    container_name: agent-tx-persistence
    image: txscience/tx-persistence
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    expose:
      - ${MONGO_PORT}
    networks:
      - agent_network

networks:
  agent_network:
    name: ${CONTAINER_NETWORK}
    external: true

